### ISSUE TITLE
Up versus downregulation

### ISSUE THREAD

**Issue by cvahlensieck** [borishejblum/dearseq#5]
Thank you for supplying dearseq!

Based on the results of dearseq, how can I differentiate downregulated from upregulated genes? As far as I understand, the method does not return fold changes, only (adjusted) p-values.

**Comment by borishejblum** [comment]
Thanks for your interest in `dearseq`.

`dearseq` does not compute fold changes because this would require a contrast comparing only 2 conditions, while dearseq sets itself to be more general and allow for testing multiple conditions at once, as well as longitudinal designs. For the same reason, it is not possible to easily define downregulated from upregulated genes in such complex designs.

That being said, if you do want to compare two conditions only, you can easily compute fold changes manually or with the functions providede by the `limma` package, and filter which ones are up or down regulated.
