### ISSUE TITLE
dearseq on datasets with more than two conditions

### ISSUE THREAD

**Issue by cvahlensieck** [borishejblum/dearseq#6]
Thank you for supplying dearseq!

Is there a standard operating procedure when having experiments with more than two conditions? I am interested in p values and fold changes between any combination of two conditions within my dataset, not only if there is an overall significant difference (e.g. LRT test).

**Comment by borishejblum** [comment]
Thanks for your interest in `dearseq`.

Unfortunately, the way `dearseq` works is by computing "overall" significance. We avoid multiple 2-group comparisons in order to retain tatistical power and to limit multiple testing.
One solution is to use descitpive measures such as manually computed fold changes to **describe** and compare your different groups once **statistical significance** is established overall.
