### ISSUE TITLE
Different results after normalization

### ISSUE THREAD

**Issue by gamabunta313** [borishejblum/dearseq#7]
I am working on a 10-sample datatlset and I have to test 2 conditions (5 vs 5). At this point Igave to dearseq raw counts and log-edgeR-TMM normalized counts and it gave me very different results. In your experience, if necessary, which normalization should I use to have reliable results?
Thanks for your help.

**Comment by borishejblum** [comment]
Hi, 

Thank you for your interest in dearseq. To be sure to understand your issue, can you provide either:
 - reproducible example of the phenomenon you are describing
 - or the code you use for log-edgeR-TMM normalization followed  by the dearseq call you are using in both cases
 
Best,
Boris

**Comment by gamabunta313** [comment]
The code to obtain edgeR-normalized counts is:
```
y <- calcNormFactors(y, method="TMM")
z<-cpm(y,normalized.lib.sizes=TRUE,log=TRUE)
```
Moreover, I have to add another strange behaviour of the function. 
I ran `dearseq::dear_seq(object = se, variables2test = "variable",  which_test = test, preprocessed = TRUE)`
If I use the "asymptotic" test I got 438 DE genes significanly deregulated, but if I use the "permutation" test I got no significant gene. How is this possible?

**Comment by borishejblum** [comment]
1. Since you have **only 10 samples**, the **asymptotic test is likely not valid** (see our publications which shows a valid control of Type-I error for the asymptotic test starting around 40 samples in our settings). Thus **you should use the permutation test**.

2. regarding tthe Edge-R norrmalization and the dearseq call, I am confused: are you using a `SummarizedExperiment` object, an `edgeR::DGEList` object, or the matrix output from `edgeR::cpm()` ?

**Comment by gamabunta313** [comment]
When I use the function with normalized=FALSE parameter I input the raw matrix on summarizedexperiment object. I suspect that my problems derive from a malinterpretation of function's parameters. Thanks for your help!
